### ISSUE TITLE
Hours being allocated to wrong person 

### ISSUE THREAD

**Issue by theMissingComma** [istrategylabs/harvest-reaper#15]
Hello, first off thanks for your work on this project!

**Problem:**
I am currently using Harvest with a Team of 7 people (4 Admins and 3 Users) to track time sheets. Upon signing into Reaper as one of the users, and then importing the hours into harvest, it allocated the hours and tasks to one of the admin profiles. No matter which User I sign into reaper with, it always allocates the hours to the same profile. If i sign in as "Freddy" and export my hours to Harvest, it puts them underneath "John's" timsheet instead.

I have tried signing out of all Google Accounts, trying different browsers, and also incognito mode. Any data still gets mis-published to the wrong account.  If you have any idea how I might overcome this I'd be very thankful.

**Update - Mostly solved:**
It seems that on the very first time exporting hours from the "problem" user account, the credentials of the admin profile were saved accidentally. It then sent all future exports to the admin profile. We have made another email account and joined it to the correct profile.

P.S. I was the user who started and deleted a comment in the other thread addressing this problem. Thanks for your quick response!

**Comment by alexbarbato** [comment]
Ahh, gotcha. To be honest I did this same thing when I was first testing the app.

You should be able to go into the Django Admin and delete the problem user so they don't have to use another email account (apologies if that's actually what you meant by making another email account). You may need them to clear the connection in their personal Harvest and Google accounts as well to truly clear all the information.

Also for what it's worth, I'm not really maintaining this project anymore because I'm not actively using Harvest where I work at the moment. Happy to help support where needed and I'm glad to see it's being used. If there is enough interest I'm happy to keep trying to working on it where people may want.

Thanks!
